# docker-compose.yml

services:
  nats:
    image: nats:2.10.16-alpine # Bruk en stabil versjon av NATS
    container_name: o-sim-nats
    ports:
      - "4222:4222" # Klientport
      - "8222:8222" # Monitoring port (HTTP)
    command: -js # Aktiver JetStream (selv om du ikke bruker den aktivt i starten, er det greit å ha den klar)
    healthcheck:
      test: ["CMD", "nats", "req", "--raw", "--timeout", "1s", "localhost:4222", "INFO"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped # Start containeren automatisk ved systemstart eller feil
    volumes:
      - nats_data:/data # Volum for vedvarende data (f.eks. for JetStream)

volumes:
  nats_data:
    driver: local