name: Build and Push Docker images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: AlarmService
            dockerfile: src/AlarmService/Dockerfile
            image: o-sim-alarmservice
          - name: AutopilotService
            dockerfile: src/AutopilotService/Dockerfile
            image: o-sim-autopilotservice
          - name: EnvironmentService
            dockerfile: src/EnvironmentService/Dockerfile
            image: o-sim-environmentservice
          - name: LoggerService
            dockerfile: src/LoggerService/Dockerfile
            image: o-sim-loggerservice
          - name: SimulatorService
            dockerfile: src/SimulatorService/Dockerfile
            image: o-sim-simulatorservice
          - name: GatewayProxyService
            dockerfile: src/GatewayProxyService/Dockerfile
            image: o-sim-gatewayproxy
          - name: WebDashboard
            dockerfile: src/Frontend/WebDashboard/Dockerfile
            image: o-sim-webdashboard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.service.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
