name: Build and Push Docker images

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: AlarmService
            context: src/AlarmService
            file: Dockerfile
            image: o-sim-alarmservice
          - name: AutopilotService
            context: src/AutopilotService
            file: Dockerfile
            image: o-sim-autopilotservice
          - name: EnvironmentService
            context: src/EnvironmentService
            file: Dockerfile
            image: o-sim-environmentservice
          - name: LoggerService
            context: src/LoggerService
            file: Dockerfile
            image: o-sim-loggerservice
          - name: SimulatorService
            context: src/SimulatorService
            file: Dockerfile
            image: o-sim-simulatorservice
          - name: GatewayProxyService
            context: src/GatewayProxyService
            file: Dockerfile
            image: o-sim-gatewayproxy
          - name: WebDashboard
            context: src/Frontend/WebDashboard
            file: Dockerfile
            image: o-sim-webdashboard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug: list repo root and build context files
        run: |
          echo "Repository root: $GITHUB_WORKSPACE"
          echo "Listing files in repository root (top-level)"
          ls -la $GITHUB_WORKSPACE || true
          echo "\nListing files in context: ${{ matrix.service.context }}"
          ls -la ${{ matrix.service.context }} || true

      - name: Debug: show Dockerfile contents (if present)
        run: |
          DOCKERFILE_PATH=${{ matrix.service.context }}/Dockerfile
          echo "Checking for Dockerfile at: $DOCKERFILE_PATH"
          if [ -f "$DOCKERFILE_PATH" ]; then
            echo "--- Dockerfile content start ---"
            sed -n '1,200p' "$DOCKERFILE_PATH" || true
            echo "--- Dockerfile content end ---"
          else
            echo "Dockerfile not found at $DOCKERFILE_PATH"
            ls -la ${{ matrix.service.context }} || true
          fi

      - name: Build and push image for ${{ matrix.service.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          # Make Dockerfile path explicit so buildx can read it reliably in Actions
          file: ${{ matrix.service.context }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # Tag with commit sha and latest. If this is a tag event we'll add the tag later.
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:latest
          # Note: disabled build cache-from/cache-to due to intermittent 'failed to calculate checksum' errors
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Tag pushed image with git tag and push
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_BASE=ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}
          SHA_TAG=${{ github.sha }}
          TAG_NAME=${{ github.ref_name }}
          SHA_IMAGE="$IMAGE_BASE:$SHA_TAG"
          TAG_IMAGE="$IMAGE_BASE:$TAG_NAME"
          echo "Pulling image $SHA_IMAGE to ensure it's available locally for tagging"
          docker pull "$SHA_IMAGE" || true
          echo "Tagging $SHA_IMAGE as $TAG_IMAGE and pushing"
          docker tag "$SHA_IMAGE" "$TAG_IMAGE"
          docker push "$TAG_IMAGE"

      - name: Scan pushed image with Trivy (HIGH/CRITICAL -> fail)
        if: startsWith(github.ref, 'refs/tags/')
        # Use the official Trivy image to scan the just-pushed image by sha tag
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:${{ github.sha }}
          echo "Scanning $IMAGE for HIGH/CRITICAL vulnerabilities..."
          docker run --rm --security-opt seccomp=unconfined aquasec/trivy:0.43.1 image --severity HIGH,CRITICAL --exit-code 1 "$IMAGE"
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
