name: .NET Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore OSim.sln /p:EnableWindowsTargeting=true /p:DisableWinExeOutputInference=true --ignore-failed-sources

            - name: Build
              run: dotnet build OSim.sln --no-restore -c Release /p:EnableWindowsTargeting=true /p:DisableWinExeOutputInference=true --ignore-failed-sources /p:BuildingInsideVisualStudio=false

            - name: Test
              run: dotnet test OSim.sln --no-build --verbosity normal /p:EnableWindowsTargeting=true /p:DisableWinExeOutputInference=true --filter "FullyQualifiedName!~WpfClient"
