name: .NET Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Restore solution
              run: dotnet restore OSim.sln /p:EnableWindowsTargeting=true /p:DisableWinExeOutputInference=true --ignore-failed-sources

            - name: Build solution
              run: dotnet build OSim.sln --no-restore -c Release /p:EnableWindowsTargeting=true /p:DisableWinExeOutputInference=true --ignore-failed-sources

            - name: Run AlarmService tests only
              run: dotnet test tests/AlarmService.Tests/AlarmService.Tests.csproj --no-build --verbosity normal
